Confinement
Riverscapes/riverscapes-tools pull request #78
Opened 2020-10-07 23:13 UTC by KellyMWhitehead

Matt, I set up confinement in the GNAT package. This can be moved or modified as needed.

Let me know if I anything sticks out as odd or bad form.

2020-10-08 22:43 UTC, MattReimer requested changes

2020-10-08 22:43 UTC, MattReimer commented on packages/gnat/.vscode/launch.json
> +        "D:\\NAR\\Projects\\Confinement\\flowlines.shp",
Totally minor thing but I wouldn't leave a hardcoded path in here. Use the .env file (take a look at rs_context for examples)

2020-10-08 22:43 UTC, MattReimer commented on packages/gnat/confinement/confinement.py
> +    feature.SetGeometry(ogr.CreateGeometryFromJson(json.dumps(mapping(geom_confining_margins))))
Take a look at this:

https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/shapefile.py#L876

Going to and from wkb is less memory and less steps.

2020-10-22 22:51 UTC, MattReimer approved these changes
Looks good to me. When you're ready to scale this up we can try the tool on a large number of hucs to see if there are issues we can't see at present.

2020-10-27 16:32 UTC, MattReimer approved these changes

2020-10-29 03:24 UTC, philipbaileynar commented
@MattReimer I just pushed the confinement report. It's super super crude right now. But it's a placeholder to take input from folks.

It required a little refactoring of the common reporting code so I ran BRAT Run once to ensure that I hadn't broken anything.

2020-10-29 03:25 UTC, MattReimer approved these changes

2020-10-29 16:56 UTC, MattReimer approved these changes

2020-10-29 16:56 UTC, merged